### ISSUE TITLE
Example for V2 plugin

### ISSUE THREAD

**Issue by smakhtin** [emersonbottero/vitepress-plugin-mermaid#12]
Hi. Looks like readme is outdated since i can't get running v2 of this plugin. I checked the src and seems like README is a bit outdated.

**Comment by emersonbottero** [comment]
there's a link to the docs there..
https://emersonbottero.github.io/vitepress-plugin-mermaid/

**Comment by smakhtin** [comment]
Are you sure this one work? I checked your examples and it looks like you tested it only in monorepo scenario where you linked it directly to library source code. Do you have a working example that follows documentation?

**Comment by emersonbottero** [comment]
You are correct.. 
I fixed the docs and create a demo.
https://github.com/emersonbottero/mermaid-vitepress-demo
