### ISSUE TITLE
Style optimization

### ISSUE THREAD

**Issue by Charles7c** [emersonbottero/vitepress-plugin-mermaid#22]
Have you noticed this problem?

![image](https://user-images.githubusercontent.com/25446948/192082628-1f6fff3e-aec2-4e0f-a46f-b5d0a6242b34.png)

**Comment by emersonbottero** [comment]
I don't have those in my docs for example.

Can you recreate the same one in my examples and see the difference comparing the html elements and styles?

**Comment by Charles7c** [comment]
What I mean by that is that when the page is rendered, the process nodes get a little big and there is an extra white space underneath each process node.
![image](https://user-images.githubusercontent.com/25446948/192104916-90d476de-f95d-4411-b437-ca5843a6ca94.png)
![image](https://user-images.githubusercontent.com/25446948/192105102-aa4858f3-284d-4b52-81b0-296fe8532aaf.png)

I wonder if these process nodes can adapt to size, similar to the style effect I used in the `Typora` editor.
Process nodes are relatively compact.
![image](https://user-images.githubusercontent.com/25446948/192104976-f2cac15b-7f92-4c48-9051-d13127c08026.png)

**Comment by emersonbottero** [comment]
strange... maybe some browser extension then?

![image](https://user-images.githubusercontent.com/12377432/192105583-1e705cf6-69fa-4e45-a252-64c50e995b03.png)

**Comment by Charles7c** [comment]
> strange... maybe some browser extension then?

Ah, I am very sorry, my brain is a little not clear today, a lot of brain can think of the crux of the problem out of trouble you. Chrome is fine.

![image](https://user-images.githubusercontent.com/25446948/192105685-09a02b29-0f03-4ead-8912-72f5437a3fd9.png)
