### ISSUE TITLE
customize the width of generated graph

### ISSUE THREAD

**Issue by xu4wang** [emersonbottero/vitepress-plugin-mermaid#26]
Is it possible to set the width of the generated flow chart, or sequence diagram?
For me the idea way is to just set the generated graph to be 100%.

**Comment by xu4wang** [comment]
Checking the generated svg, there is always a max-width property set for every generated graph.

Is there a way to set this max-width to 100% instead of calculated value?

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/311397/208289284-70e2d95f-a714-4f0f-9baa-2ca87a0397bb.png">

**Comment by emersonbottero** [comment]
You should open an issue in mermaid since they are the ones computing the SVG
