### ISSUE TITLE
Please add a way to set a class for parent div container

### ISSUE THREAD

**Issue by dominikcz** [emersonbottero/vitepress-plugin-mermaid#37]
It would be nice to have the ability to add a class to parent div container. In Vuepress there was a class "mermaid" added by default, but there is no selector now to aid with styling.

**Comment by dominikcz** [comment]
Just additional note: if you don't want to add extra functionality like that, then maybe just add some default class like `mermaid` or something similar? It's really hard to reliably style diagrams without restricting selectors to parent container. I want to change things that are not available through theme configuration.

**Comment by emersonbottero** [comment]
````html
<div class="my-class">
```mermaid
flowchart TD
  Start --> Stop
```
</div>

````

**Comment by dominikcz** [comment]
Yes, I'm aware of that option, but it's troublesome having to repeat that for every graph, not to mention mixing html with markdown... Please see #40 for my idea of accomplishing this task

**Comment by dominikcz** [comment]
hi, any plans on merging it to master?

**Comment by emersonbottero** [comment]
I'll add a static mermaid class to it.
trying to remove the mindmap dependcy also.
