### ISSUE TITLE
@mermaid-js/mermaid-mindmap as dev dependencies

### ISSUE THREAD

**Issue by dominikcz** [emersonbottero/vitepress-plugin-mermaid#38]
Since merging #32 there is a side effect, that you have to add @mermaid-js/mermaid-mindmap as devDependency to main project. I suppose it would be better DX if vitepress-plugin-mermaid handled it internally

`[vite]: Rollup failed to resolve import "@mermaid-js/mermaid-mindmap" from "(...)vitepress-plugin-mermaid/dist/mermaid.ts".`

**Comment by emersonbottero** [comment]
Probably I can try to import dynamic and if it fails I just ignore it and just log package not found...

**Comment by dominikcz** [comment]
Seems like a good idea for me. Now it is just strange that even if I don't plan to use mindmaps anywhere I have to use:
`npm i -D  @mermaid-js/mermaid-mindmap` in my vitepress projects.

**Comment by emersonbottero** [comment]
removed as dependency
