### ISSUE TITLE
SyntaxError: Importing binding name 'default' cannot be resolved by star export entries.

### ISSUE THREAD

**Issue by glennsc** [emersonbottero/vitepress-plugin-mermaid#39]
1. I followed the [configuration instructions](https://emersonbottero.github.io/vitepress-plugin-mermaid/guide/getting-started.html#setup-it-up) in the docs.
2. On running `docs:dev` nothing renders and and I get the following error in the browser console:

```
SyntaxError: Importing binding name 'default' cannot be resolved by star export entries.
```

My `.vitepress.config.js` looks like this:

```js
/**
 * @type {import('vitepress').UserConfig}
 */

import { defineConfig } from "vitepress";
import { withMermaid } from "vitepress-plugin-mermaid";

export default withMermaid(
  defineConfig({
    lang: "en-us",
    title: "My site",
    description: "My description",
    cleanUrls: true,
    lastUpdated: true,

    themeConfig: {
      nav: [
        { text: "Docs", link: "/getting-started/overview" },
        { text: "API Reference", link: "/api-ref" },
      ],

      footer: {
        message: "Confidential. For internal use only.",
        copyright: "Copyright © 2023, Me",
      },
    },
  })
);
```

Package.json:

```json
{
  "name": "my-site",
  "main": "index.js",
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@mermaid-js/mermaid-mindmap": "^9.3.0",
    "mermaid": "^9.3.0",
    "vitepress": "1.0.0-alpha.45",
    "vitepress-plugin-mermaid": "^2.0.10",
    "vue": "^3.2.47"
  }
}
```

Anything obvious I'm doing wrong?

<img width="566" alt="image" src="https://user-images.githubusercontent.com/829567/218198364-d8d081a7-7900-4c1a-928c-1ececc5bca8d.png">

**Comment by emersonbottero** [comment]
Is not .vitepress.config.js
It should be 
.vitepress/config.js

**Comment by glennsc** [comment]
My apologies, that was just a typo when I wrote the issue.  Yes, my file is in `.vitepress/config.js` 

I created a minimal Vitepress install, and added the mermaid plugin per the docs, and still get the same error.

https://codesandbox.io/p/github/aigency/vpm/main?file=%2Fdocs%2F.vitepress%2Fconfig.js

**Comment by emersonbottero** [comment]
try the solution mention [here](https://github.com/emersonbottero/vitepress-plugin-mermaid/issues/33#issuecomment-1410538782)

**Comment by glennsc** [comment]
Okay, yes. Dropping a `vite.config.js` into `docs` with:
```js
export default {
  optimizeDeps: { include: ['moment-mini', '@braintree/sanitize-url'] },
}
```
and then 
```
pnpm add moment-mini @braintree/sanitize-url -D
```
stopped the errors throwing in dev.  I see mermaid [merged your PR](https://github.com/mermaid-js/mermaid/pull/4034) fixing this so I assume we'll be able to remove this workaround soon.  Really appreciate your help, and love this plugin.
