### ISSUE TITLE
"vitepress-plugin-mermaid" has no exported member 'withMermaid'

### ISSUE THREAD

**Issue by Intevel** [emersonbottero/vitepress-plugin-mermaid#46]
![image](https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/59223342/481837a3-f762-4629-8a07-cd36aa30cb47)

**Comment by emersonbottero** [comment]
It exports in here
https://github.com/emersonbottero/vitepress-plugin-mermaid/blob/d525ea65046dc1d041e99e07bc0f4a6c7540eb82/src/index.ts#L14

Can you share your repo?

**Comment by CorvusYe** [comment]
Hi, @emersonbottero 

I also encountered this problem. 
Perhaps we need to check if the source code of Github matches the package of NPM.

https://www.npmjs.com/package/vitepress-plugin-mermaid?activeTab=code

**Comment by Intevel** [comment]
> Hi, @emersonbottero 
> 
> 
> 
> I also encountered this problem. 
> 
> Perhaps we need to check if the source code of Github matches the package of NPM.
> 
> 
> 
> https://www.npmjs.com/package/vitepress-plugin-mermaid?activeTab=code
> 
> 
> 
> 

It doesn't match. On npm only the render function is exported.

**Comment by Intevel** [comment]
@emersonbottero Can you please publish a new version?

**Comment by emersonbottero** [comment]
can you lock the version to the previous working one?
My fix PR should be released this Wednesday by mermaid team and I have an unpublished version with lot of fixes waiting just for that..

**Comment by CorvusYe** [comment]
This doesn't seem to work very well. Thanks all the same.

![image](https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/15630211/3b093938-8d75-46e0-9840-b81cfc001885)

package.json : 
```json
{
  "name": "ngbatis-docs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "vitepress": "1.0.0-alpha.76",
    "vitepress-plugin-mermaid": "^2.0.8"
  }
}

```

**Comment by emersonbottero** [comment]
try that combination.. 
![image](https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/12377432/900b62d4-a9be-4969-a2f2-7f710b9d6232)

you must remove ^ from the mermaid version

**Comment by Intevel** [comment]
> try that combination.. ![image](https://user-images.githubusercontent.com/12377432/240068555-900b62d4-a9be-4969-a2f2-7f710b9d6232.png)
> 
> you must remove ^ from the mermaid version

But this is a workaround, not a real fix. Maybe you just publish the current version?

**Comment by emersonbottero** [comment]
can you share your repo?
and the problem is with mermaid.. no this plugin.. 
once mermaid fix it you can install the last version of mermaid

**Comment by CorvusYe** [comment]
This my repo, but it doesn't depends this plugin now.

https://github.com/graph-cn/ngbatis-docs

 mermaid page
https://github.com/graph-cn/ngbatis-docs/blob/master/docs/step-forward-docs/operation-sequence.md

**Comment by emersonbottero** [comment]
![image](https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/12377432/e94de03f-d3d5-4d0b-90c4-90e54ab87f8e)

I made an PR for you

**Comment by CorvusYe** [comment]
> ![image](https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/12377432/e94de03f-d3d5-4d0b-90c4-90e54ab87f8e)
> 
> I made an PR for you

I see the [effect](https://graph-cn.github.io/ngbatis-docs/step-forward-docs/operation-sequence.html). This is awesome. Thank you so much.

**Comment by skanehira** [comment]
I have same problem.
I cannot find `index.ts` in the dist direcotry.

```
skanehira@gorilla this-week-in-gorilla/node_modules/vitepress-plugin-mermaid 
$ tree .   
.
├── LICENSE
├── README.md
├── dist
│   ├── Mermaid.vue
│   ├── mermaid.ts
│   ├── vitepress-plugin-mermaid.es.mjs
│   └── vitepress-plugin-mermaid.umd.js
├── node_modules
└── package.json

3 directories, 7 files
```

I tried the following, but index.ts still does not exist.

https://github.com/emersonbottero/vitepress-plugin-mermaid/issues/46#issuecomment-1558191500

How can I solve this problem?
My repo is https://github.com/skanehira/this-week-in-gorilla

**Comment by Intevel** [comment]
It works for some reason to import, however it still shows as an error. What to use `@ts-expect-error` for TypeScript projects

**Comment by Intevel** [comment]
Still occurs in 2.0.11

**Comment by Intevel** [comment]
Fixed in #48, for temporary usage you can use `@intevel/vitepress-plugin-mermaid@2.0.15`

**Comment by CorvusYe** [comment]
@Intevel 
![image](https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/15630211/96822aa6-e54d-4294-a7a2-231a8a37fd2d)
In my environment, although it also reports errors, it is indeed usable.

**Comment by Intevel** [comment]
> @Intevel ![image](https://user-images.githubusercontent.com/15630211/250842357-96822aa6-e54d-4294-a7a2-231a8a37fd2d.png) In my environment, although it also reports errors, it is indeed usable.

I just made a PR which fixes that, until its released you can use my version of publish: 

```
npm install @intevel/vitepress-plugin-mermaid@2.0.15
// or 
yarn add @intevel/vitepress-plugin-mermaid@2.0.15
