### ISSUE TITLE
Uncaught SyntaxError: The requested module '/@fs/D:/Workspace/vitesse/node_modules/dayjs/dayjs.min.js?v=885b2e35' does not provide an export named 'default' (at mermaid-ae477ddf.js?v=885b2e35:2:8)

### ISSUE THREAD

**Issue by ezzle** [emersonbottero/vitepress-plugin-mermaid#47]
Hi,

## Error when trying to use the plugin.

`Uncaught SyntaxError: The requested module '/@fs/D:/Workspace/vitesse/node_modules/dayjs/dayjs.min.js?v=885b2e35' does not provide an export named 'default' (at mermaid-ae477ddf.js?v=885b2e35:2:8)`

## My config 

`import { defineConfig } from 'vitepress'
import { withMermaid } from "vitepress-plugin-mermaid";

export default withMermaid(
// https://vitepress.dev/reference/site-config
defineConfig({
  title: ".....",
  description: "......",
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Examples', link: '/markdown-examples' }
    ],

    sidebar: [
      {
        text: 'Examples',
        items: [
          { text: 'Markdown Examples', link: '/markdown-examples' },
          { text: 'Runtime API Examples', link: '/api-examples' }
        ]
      }
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/ezzle' }
    ],

    footer: {
      message: 'Released under the <a href="https://github.com/vuejs/vitepress/blob/main/LICENSE">MIT License</a>.',
      copyright: 'Copyright © 2023-present <a href="...../">....</a>'
    }
  },
  mermaid: {
    // refer https://mermaid.js.org/config/setup/modules/mermaidAPI.html#mermaidapi-configuration-defaults for options
  },
})
);

`

## And my package.json

`{
  "devDependencies": {
    "@mermaid-js/mermaid-mindmap": "^9.3.0",
    "mermaid": "^9.4.3",
    "vitepress": "^1.0.0-beta.2",
    "vitepress-plugin-mermaid": "^2.0.10"
  },
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
  "dependencies": {
    "@popperjs/core": "^2.11.8",
    "bootstrap": "^5.3.0",
    "dayjs": "^1.11.8"
  }
}
`
## My .md file for testing
`
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
`

**Comment by emersonbottero** [comment]
https://github.com/emersonbottero/vitepress-demo2
working example.. pay attention to the mermaid version used.

**Comment by Takeno-hito** [comment]
I had the same situation as Issue and solved it by downgrading the Mermaid version from 9.4.3 to 9.1.0. I wish you would support 9.4.3 or explain in the README that it does not work with 9.4.3 :)

**Comment by emersonbottero** [comment]
Hi all.. 
just publish a new version.. could someone test it with the latest mermaid version?
there should be no need for the vite.config.ts anymore

**Comment by ezzle** [comment]
> Hi all.. just publish a new version.. could someone test it with the latest mermaid version? there should be no need for the vite.config.ts anymore

Can you adapt the doc ? 

- Which Vitepress version  [1.0.0-beta.5](https://github.com/vuejs/vitepress/compare/v1.0.0-beta.4...v1.0.0-beta.5) ?
- Version of Mermaid ?

**Comment by emersonbottero** [comment]
Try with the latest version of each. 😃

**Comment by glennsc** [comment]
I tried bringing every version up to date, deleting `pnmp-lock.yaml` and `node_modules/`, reinstalling with this dependency list:
```
  "dependencies": {
    "markdown-it-footnote": "^3.0.3",
    "mermaid": "10.2.4",
    "vitepress": "1.0.0-beta.5",
    "vitepress-plugin-mermaid": "^2.0.11",
    "vue": "^3.3.4"
  }
  ```
  Running `pnpm docs:build && pnpm docs:preview` seems to work well, but `pnpm docs:dev` generates the error described above:
  
  > The requested module '/@fs/Users/.../node_modules/.pnpm/dayjs@1.11.9/node_modules/dayjs/dayjs.min.js?v=57ffa4d3' does not provide an export named 'default' (at mermaid-aad43469.js?v=57ffa4d3:2:8)

**Comment by emersonbottero** [comment]
That happens whenever you use a chart with dates since days is not really using module. 
I'm trying to fix those but there is no easy solution for now.

**Comment by emersonbottero** [comment]
could you check again with version 2.0.13

**Comment by glennsc** [comment]
With 2.0.13, and the following package.json:

```
  "dependencies": {
    "markdown-it-footnote": "^3.0.3",
    "mermaid": "10.2.4",
    "vitepress": "1.0.0-beta.5",
    "vitepress-plugin-mermaid": "^2.0.13",
    "vue": "^3.3.4"
  }
```
A fresh build of ppm-lock.yaml and node_modules, running `pnpm docs:dev` I get the warnings:

```
Failed to resolve dependency: @braintree/sanitize-url, present in 'optimizeDeps.include'
Failed to resolve dependency: dayjs, present in 'optimizeDeps.include'
Failed to resolve dependency: debug, present in 'optimizeDeps.include'
Failed to resolve dependency: cytoscape-cose-bilkent, present in 'optimizeDeps.include'
Failed to resolve dependency: cytoscape, present in 'optimizeDeps.include'
```

And then running Vitepress I get the same error:

> mermaid-aad43469.js?v=97c8e166:2 Uncaught SyntaxError: The requested module '/@fs/.../node_modules/.pnpm/dayjs@1.11.9/node_modules/dayjs/dayjs.min.js?v=97c8e166' does not provide an export named 'default' (at mermaid-aad43469.js?v=97c8e166:2:8)

Running `pnpm docs:build && pnpm docs:preview` works great, just as before.

**Comment by emersonbottero** [comment]
@glennsc  could you compare with https://github.com/emersonbottero/vitepress-demo2?
it works for me.

**Comment by hojas** [comment]
> With 2.0.13, and the following package.json:
> 
> ```
>   "dependencies": {
>     "markdown-it-footnote": "^3.0.3",
>     "mermaid": "10.2.4",
>     "vitepress": "1.0.0-beta.5",
>     "vitepress-plugin-mermaid": "^2.0.13",
>     "vue": "^3.3.4"
>   }
> ```
> 
> A fresh build of ppm-lock.yaml and node_modules, running `pnpm docs:dev` I get the warnings:
> 
> ```
> Failed to resolve dependency: @braintree/sanitize-url, present in 'optimizeDeps.include'
> Failed to resolve dependency: dayjs, present in 'optimizeDeps.include'
> Failed to resolve dependency: debug, present in 'optimizeDeps.include'
> Failed to resolve dependency: cytoscape-cose-bilkent, present in 'optimizeDeps.include'
> Failed to resolve dependency: cytoscape, present in 'optimizeDeps.include'
> ```
> 
> And then hitting `http://localhost:5173` I get the same error:
> 
> > mermaid-aad43469.js?v=97c8e166:2 Uncaught SyntaxError: The requested module '/@fs/.../node_modules/.pnpm/dayjs@1.11.9/node_modules/dayjs/dayjs.min.js?v=97c8e166' does not provide an export named 'default' (at mermaid-aad43469.js?v=97c8e166:2:8)
> 
> Running `pnpm docs:build && pnpm docs:preview` works great, just as before.

Same issue with pnpm, use npm or yarn will be ok.

**Comment by glennsc** [comment]
@emersonbottero Comparing to you I got the same behavior, then switched from `pnpm` to `npm` and the issue **resolved**. So it appears there is some sort of incompatibility when `pnpm` (my version: 8.6.7) is used!

**Comment by emersonbottero** [comment]
I updated the docs informing this.

**Comment by Red-Asuka** [comment]
I would like to inquire if there are plans to support PNPM, and what the possible timeline might be? Thank you.

**Comment by ATQQ** [comment]
I use pnpm and I solve this problem in my theme pkg [@sugarat/theme](https://github.com/ATQQ/sugar-blog/tree/master/packages/theme)

I custom implemented the withMermaid method

Here's my code

https://github.com/ATQQ/sugar-blog/blob/dce862580fc829475df25871b8b069c97de9c8ca/packages/theme/src/node.ts#L312-L330

Some diff
1. I use require replace import
2. I  remove optimizeDeps config
3. other alias

```js
config.vite.resolve.alias = [
    ...aliasObjectToArray({
      ...config.vite.resolve.alias,
      'cytoscape/dist/cytoscape.umd.js': 'cytoscape/dist/cytoscape.esm.js',
      mermaid: 'mermaid/dist/mermaid.esm.mjs'
    }),
    { find: /^dayjs\/(.*).js/, replacement: 'dayjs/esm/$1' }
  ]
```
···

---
Welcome to experience my theme, a line of code （😄）

```sh
npm create @sugarat/theme@latest
```

**Comment by emersonbottero** [comment]
> I would like to inquire if there are plans to support PNPM, and what the possible timeline might be? Thank you.

could you delete node_modules and pnpm-lock and try 
pnpm install --shamefully-hoist ? 

thanks

**Comment by emersonbottero** [comment]
> I use pnpm and I solve this problem in my theme pkg [@sugarat/theme](https://github.com/ATQQ/sugar-blog/tree/master/packages/theme)
> 
> I custom implemented the withMermaid method
> 
> Here's my code
> 
> https://github.com/ATQQ/sugar-blog/blob/dce862580fc829475df25871b8b069c97de9c8ca/packages/theme/src/node.ts#L312-L330
> 
> Some diff
> 
> 1. I use require replace import
> 2. I  remove optimizeDeps config
> 3. other alias
> 
> ```js
> config.vite.resolve.alias = [
>     ...aliasObjectToArray({
>       ...config.vite.resolve.alias,
>       'cytoscape/dist/cytoscape.umd.js': 'cytoscape/dist/cytoscape.esm.js',
>       mermaid: 'mermaid/dist/mermaid.esm.mjs'
>     }),
>     { find: /^dayjs\/(.*).js/, replacement: 'dayjs/esm/$1' }
>   ]
> ```
> 
> ···
> 
> Welcome to experience my theme, a line of code （😄）
> 
> ```shell
> npm create @sugarat/theme@latest
> ```

didn't manage to replicate , would you mind trying to make an PR ? 🙂

**Comment by ATQQ** [comment]
> > I use pnpm and I solve this problem in my theme pkg [@sugarat/theme](https://github.com/ATQQ/sugar-blog/tree/master/packages/theme)
> > I custom implemented the withMermaid method
> > Here's my code
> > https://github.com/ATQQ/sugar-blog/blob/dce862580fc829475df25871b8b069c97de9c8ca/packages/theme/src/node.ts#L312-L330
> > Some diff
> > 
> > 1. I use require replace import
> > 2. I  remove optimizeDeps config
> > 3. other alias
> > 
> > ```js
> > config.vite.resolve.alias = [
> >     ...aliasObjectToArray({
> >       ...config.vite.resolve.alias,
> >       'cytoscape/dist/cytoscape.umd.js': 'cytoscape/dist/cytoscape.esm.js',
> >       mermaid: 'mermaid/dist/mermaid.esm.mjs'
> >     }),
> >     { find: /^dayjs\/(.*).js/, replacement: 'dayjs/esm/$1' }
> >   ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ···
> > Welcome to experience my theme, a line of code （😄）
> > ```shell
> > npm create @sugarat/theme@latest
> > ```
> 
> didn't manage to replicate , would you mind trying to make an PR ? 🙂

No problem, just for the past two days, I'll do a whole PR
