### ISSUE TITLE
Support SSG?

### ISSUE THREAD

**Issue by Jeff-Tian** [emersonbottero/vitepress-plugin-mermaid#52]
Can we generate all the mermaid graphs during build time?

**Comment by emersonbottero** [comment]
If you want that you should see the repo for the docs on the oficial roolup repo

**Comment by Jeff-Tian** [comment]
Could you share the link? @emersonbottero  Didn't find any related content:

<img width="1368" alt="image" src="https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/3367820/f5a32beb-bfb0-4818-87e5-5656b3c3af11">

In the mean time, I am considering using the `markdown-it-mermaid` plugin so in the end, the mermaid graphs can be generated during the vite-press building step.

**Comment by Jeff-Tian** [comment]
Found another thread: https://github.com/mermaid-js/mermaid/issues/3650, seems it's very hard.
