### ISSUE TITLE
Error when rendering mermaid chart on vitepress instance

### ISSUE THREAD

**Issue by jcstein** [emersonbottero/vitepress-plugin-mermaid#55]
When settting up mermaid chart in vitepress site, I run into these build dep errors:

```bash
1:32:42 PM [vitepress] .vitepress/config.ts changed, restarting server...

Failed to resolve dependency: @braintree/sanitize-url, present in 'optimizeDeps.include'
Failed to resolve dependency: dayjs, present in 'optimizeDeps.include'
Failed to resolve dependency: debug, present in 'optimizeDeps.include'
Failed to resolve dependency: cytoscape-cose-bilkent, present in 'optimizeDeps.include'
Failed to resolve dependency: cytoscape, present in 'optimizeDeps.include'
```

on this commit, i added it commented out: https://github.com/jcstein/rollkit-vitepress/commit/ba2fd9bd492c8e59356017af0ae259aa443fa99c

and on this branch i have the version that I was trying: https://github.com/jcstein/rollkit-vitepress/tree/jcs/mermaid

**Comment by emersonbottero** [comment]
could you delete node_modules and pnpm-lock and try
pnpm install --shamefully-hoist ?

if still doesn´t work could you try replacing pnpm with npm?

**Comment by jcstein** [comment]
that worked! i am running into an [issue](https://github.com/jcstein/rollkit-vitepress/actions/runs/5670729578) using github pages so think i will also switch to npm! thanks again for the help
