### ISSUE TITLE
Error: can't reslove import "@/public/logo.jpeg" from 'xxx' when build

### ISSUE THREAD

**Issue by scattter** [emersonbottero/vitepress-plugin-mermaid#56]
In my project, i can successfully use this plugin in my local, but will meet error when i try to build it.

log error:
```
building client + server bundles...[vite]: Rollup failed to resolve import "@/public/logo.jpeg" from "docs/project/50projects50days/viewComponent/ScratchTicket.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

my vitepress's config:
```javascript
export default withMermaid(defineConfig({
  vite: {
    resolve: {
      alias: [
        {
          find: '@',
          replacement: resolve(__dirname, '../../docs'),
        },
        {
          find: '@viewComponents',
          replacement: resolve(__dirname, '../../docs/project/50projects50days/viewComponent'),
        },
      ],
      extensions: ['.js', '.ts', '.jsx', '.tsx', '.json']
    },
  },
  // ... other config
}))
```

the repo address: https://github.com/scattter/scattter.github.io

thank you very much

**Comment by emersonbottero** [comment]
Actually the problem is I didn't consider alias as an array, only as an object.. 
could you try to replace your alias to
```js
 alias: {
          "@": resolve(__dirname, "../../docs"), // 这里拆分配置后根目录发生了变化
          "@viewComponents": resolve(
            __dirname,
            "../../docs/project/50projects50days/viewComponent"
          ), // 这里拆分配置后根目录发生了变化
        },
```
I'll leave this as a bug but let me know if this has fix your problem.

**Comment by scattter** [comment]
Thank you very much, it works with object type.

But i think it will better if it also support array type. So i create a pr in this project, hope get your reply.
pr address: https://github.com/emersonbottero/vitepress-plugin-mermaid/pull/57

**Comment by scattter** [comment]
> Actually the problem is I didn't consider alias as an array, only as an object.. could you try to replace your alias to
> 
> ```js
>  alias: {
>           "@": resolve(__dirname, "../../docs"), // 这里拆分配置后根目录发生了变化
>           "@viewComponents": resolve(
>             __dirname,
>             "../../docs/project/50projects50days/viewComponent"
>           ), // 这里拆分配置后根目录发生了变化
>         },
> ```
> 
> I'll leave this as a bug but let me know if this has fix your problem.

Thank you very much, it works with object type.

But i think it will better if it also support array type. So i create a pr in this project, hope get your reply.
pr address: https://github.com/emersonbottero/vitepress-plugin-mermaid/pull/57
