### ISSUE TITLE
VSCode IntelliSense lost after switching to `withMermaid()` helper

### ISSUE THREAD

**Issue by sagargurtu** [emersonbottero/vitepress-plugin-mermaid#59]
As in the title. VSCode IntelliSense is lost after switching from `defineConfig()` to `withMermaid()` helper. Code complete suggestions no longer show up and unsupported properties can be freely added to the config.

**Comment by emersonbottero** [comment]
Is working for me.. 
![image](https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/12377432/cf76a6f8-d68d-4e07-bb82-f299c5676de8)

**Comment by sagargurtu** [comment]
I can't seem to reproduce the issue with latest version of `vitepress`. I had an older version of `vitepress` in my project when I faced this. I'll go ahead and close this issue.
