### ISSUE TITLE
TypeError for withMermaid config arguments

### ISSUE THREAD

**Issue by aeyll-11** [emersonbottero/vitepress-plugin-mermaid#62]
Hello, I encountered this type error while employing defineConfig within the context of withMermaid.
```
Argument of type 'UserConfigExport<Config>' is not assignable to parameter of type 'UserConfig<any>'.
Type 'Promise<UserConfig<Config>>' has no properties in common with type 'UserConfig<any>'.ts(2345)
```
defineConfig in Vitepress yields UserConfigExport<DefaultTheme.Config> rather than a UserConfig<any>
```
declare function defineConfig(config: UserConfigExport<DefaultTheme.Config>): UserConfigExport<DefaultTheme.Config>;
```

**Comment by brc-dd** [comment]
defineConfig is not needed if you're using withMermaid

**Comment by aeyll-11** [comment]
@brc-dd Why do the repository use it that way then?
https://github.com/emersonbottero/vitepress-plugin-mermaid/blob/main/docs/.vitepress/config.js

**Comment by brc-dd** [comment]
That's probably to provide hints for theme part. But which vitepress version are you on? It doesn't use `UserConfigExport` for defineConfig.

**Comment by aeyll-11** [comment]
I use the latest "mermaid": "^10.5.0" 
line 41
https://github.com/vuejs/vitepress/blob/main/src/node/config.ts

**Comment by brc-dd** [comment]
That is just exported no longer used by defineConfig or anything. And IIRC beta 2 was the only version having that. Update your version to rc or something.
