### ISSUE TITLE
Errors after update Vitepress to 1.0.0-rc.26

### ISSUE THREAD

**Issue by koddr** [emersonbottero/vitepress-plugin-mermaid#63]
Hi, @emersonbottero!

Thanks for build and support of this plugin, it's very useful for me.

After update Vitepress to `v1.0.0-rc.26`, I see this errors in `./docs/.vitepress/config.mts` config file:

1. In user config block:

<img width="587" alt="2023-11-17 07 48 55" src="https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/11155743/fe452586-c91d-4713-b4f2-a3ba00fadd98">

2. In export block:

<img width="1119" alt="2023-11-17 07 49 21" src="https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/11155743/72f02fb3-36f3-4622-b3a8-8b71c7c63dd3">

How to solve it? Maybe, `vitepress-plugin-mermaid` must be updated to the latest Vitepress version too?

**Comment by emersonbottero** [comment]
can you try again ?

**Comment by koddr** [comment]
@emersonbottero yep, after update to the latest VitePress (v1.0.0-rc.31) this error is gone.
