### ISSUE TITLE
Diagram is not shown in production build.

### ISSUE THREAD

**Issue by bonyuta0204** [emersonbottero/vitepress-plugin-mermaid#64]
Hi @emersonbottero 

I've encountered a problem when using this plugin with VitePress versions higher than 1.0.0-rc.26.

## Description
There's an issue in the production build. Since the update to [VitePress 1.0.0-rc.26](https://github.com/vuejs/vitepress/compare/v1.0.0-rc.25...v1.0.0-rc.26), the Mermaid diagrams do not appear when building VitePress in production mode.

## Steps to Reproduce
Affected VitePress version: 1.0.0-rc.26 and above
To reproduce, build and preview using the following commands:
```bash
pnpm run docs:build
pnpm run docs:preview
```

## Details
Here's a comparison of the behavior in development vs. production:

| Development | Production |
|-------------|------------|
| ![Screenshot of Development Mode](https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/19663115/a16cc4c9-a83d-4377-ade4-4b162e66b898) | ![Screenshot of Production Mode](https://github.com/emersonbottero/vitepress-plugin-mermaid/assets/19663115/04818ace-978f-4e6c-ab21-a5d0360a441a) |

## Possible Cause
- It appears that `Mermaid` is not being installed globally.
- In the [plugin code](https://github.com/emersonbottero/vitepress-plugin-mermaid/blob/4fe352b70704d6668cdd9ce90f0c04569e6bedf4/src/mermaid-plugin.ts#L46-L47), the transform method replaces comments and installs global components. However, in the production build, the targeted comment disappears before the transformation occurs.
- This issue might be related to the Vite update to version 5.0.0.

**Comment by bonyuta0204** [comment]
I will try to fix this issue!

**Comment by bonyuta0204** [comment]
Fixed by #65.

**Comment by Rodeoclash** [comment]
Hmm, I've just run into this now as well (no diagrams in production but they show in development). I'm on vitepress 1.0.0-rc.31 and vitepress-plugin-mermaid 2.0.16

Might be that the problem has come back again for some reason. I'll try and debug what is going on.

**Comment by brolnickij** [comment]
> Hmm, I've just run into this now as well (no diagrams in production but they show in development). I'm on vitepress 1.0.0-rc.31 and vitepress-plugin-mermaid 2.0.16
> 
> Might be that the problem has come back again for some reason. I'll try and debug what is going on.

same

**Comment by Rodeoclash** [comment]
So I got to the bottom of this in the end. I had https://vitepress.dev/guide/mpa-mode enabled which turned off the JavaScript required to show the Mermaid charts (makes sense).

I've gone with embedding an image of the charts (generated from a URL) as I require basic auth on some of the endpoints in our docs (provided by Cloudflare workers).

Anyway, hope this helps someone else.

**Comment by emersonbottero** [comment]
Add support for scrip client.
@Rodeoclash thanks for debugging the problem

**Comment by Red-Asuka** [comment]
I faced the same issue with:

- vitepress: 1.0.0-rc.31
- vitepress-plugin-mermaid: 2.0.15
- mermaid: 10.5.0

Downgrading vitepress to 1.0.0-rc.20 resolved the problem.

**Comment by dkattan** [comment]
> I faced the same issue with:
> 
> * vitepress: 1.0.0-rc.31
> * vitepress-plugin-mermaid: 2.0.15
> * mermaid: 10.5.0
> 
> I upgraded vitepress-plugin-mermaid to 2.0.16 to solve this issue.

This worked for me!

Simply upgrading vitepress from rc.13 to rc.31 and vitepress-plugin-mermaid from 2.0.14 to 2.0.16 didn't do it. I had to also update mermaid from 10.4.0 to 10.5.0

**Comment by emersonbottero** [comment]
It is working with the last version of mermaid 11+
